package medi.voll.api.medico;


// O ENUM SERVE PARA QUANDO TEMOS POSSIBILIDADES DENTRO DE UMA VARIAVEL
public enum Especialidade {
    ORTOPEDIA,
    CARDIOLOGIA,
    GINECOLOGIA,
    DERMATOLOGIA;
}
